[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
cache_path = "cache"
solc_version = "0.8.30"
optimizer = false
verbosity = 2

[fmt]
line_length = 80
tab_width = 4
bracket_spacing = true
int_types = "long"
multiline_func_header = "params_first"
quote_style = "double"
number_underscore = "thousands"